language: java

jdk:
- oraclejdk8

branches:
  only:
    - ssu-calendar

script:
  - bundle exec cd Template_Skill && bundle exec gradle check
  - bundle exec cd Template_Skill && bundle exec gradle fatJar

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
